//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mpho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int Ass_Id { get; set; }
        public string Ass_name { get; set; }
        public int Cond_Id { get; set; }
        public int Brand_Id { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Condition Condition { get; set; }
    }
}
